<a href="https://colab.research.google.com/github/teja12345678909876/dataanalyst/blob/main/index%5B06_12_2024%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from opendatasets) (4.66.6)
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from opendatasets) (8.1.7)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2024.8.30)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.10)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [3]:
data = pd.read_csv('/content/dataset(in).csv')

NameError: name 'pd' is not defined

In [4]:
import pandas as pd  # Import the pandas library and assign it the alias 'pd'

data = pd.read_csv('/content/dataset(in).csv')

In [5]:
data

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,1/4/2015 0:00,182,3.0,2.0,93.0,6.0,3,0,1,3
1,1/4/2015 1:00,138,3.0,2.5,93.0,5.0,1,0,1,3
2,1/4/2015 2:00,134,2.5,2.5,96.5,0.0,1,0,1,3
3,1/4/2015 3:00,72,2.0,2.0,100.0,0.0,1,0,1,3
4,1/4/2015 4:00,47,2.0,0.0,93.0,6.5,1,0,1,3
...,...,...,...,...,...,...,...,...,...,...
17409,1/3/2017 19:00,1042,5.0,1.0,81.0,19.0,3,0,0,3
17410,1/3/2017 20:00,541,5.0,1.0,81.0,21.0,4,0,0,3
17411,1/3/2017 21:00,337,5.5,1.5,78.5,24.0,4,0,0,3
17412,1/3/2017 22:00,224,5.5,1.5,76.0,23.0,4,0,0,3
17413,1/3/2017 23:00,139,5.0,1.0,76.0,22.0,2,0,0,3

In [20]:
data.loc[10, 'cnt']

528

In [21]:
data.iloc[10] #.iloc[]: This is a special feature (called an accessor) provided by Pandas. It allows you to access rows and columns in your DataFrame using their integer positions (like their index numbers).

timestamp       1/4/2015 10:00
cnt                        528
t1                         3.0
t2                        -0.5
hum                       93.0
wind_speed                12.0
weather_code                 3
is_holiday                   0
is_weekend                   1
season                       3
Name: 10, dtype: object

In [11]:
data.drop('cnt', axis=1) #drop(): This is the method used to remove rows or columns from the DataFrame. axis=1: This argument tells drop() to remove a column. If you were removing a row, you would use axis=0.

,timestamp,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,1/4/2015 0:00,3.0,2.0,93.0,6.0,3,0,1,3
1,1/4/2015 1:00,3.0,2.5,93.0,5.0,1,0,1,3
2,1/4/2015 2:00,2.5,2.5,96.5,0.0,1,0,1,3
3,1/4/2015 3:00,2.0,2.0,100.0,0.0,1,0,1,3
4,1/4/2015 4:00,2.0,0.0,93.0,6.5,1,0,1,3
...,...,...,...,...,...,...,...,...,...
17409,1/3/2017 19:00,5.0,1.0,81.0,19.0,3,0,0,3
17410,1/3/2017 20:00,5.0,1.0,81.0,21.0,4,0,0,3
17411,1/3/2017 21:00,5.5,1.5,78.5,24.0,4,0,0,3
17412,1/3/2017 22:00,5.5,1.5,76.0,23.0,4,0,0,3
17413,1/3/2017 23:00,5.0,1.0,76.0,22.0,2,0,0,3